# Generated by Django 4.0.4 on 2022-05-26 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 11, 9, 43, 415629, tzinfo=utc)),
        ),
    ]
