# Generated by Django 4.0.4 on 2022-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='sub_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='sub_exp',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='calls',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('create', 'create'), ('paid', 'paid'), ('done', 'done')], default='create', max_length=200),
        ),
    ]
