# Generated by Django 4.0.4 on 2022-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_payment_sub_date_payment_sub_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub_calls',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
