# Generated by Django 4.0.4 on 2022-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment_sub_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sub_calls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sub_exp',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sub_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sub_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
