# Generated by Django 4.0.4 on 2022-05-26 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 11, 10, 37, 788231, tzinfo=utc)),
        ),
    ]
